changelog:
  exclude:
    authors:
    - renovate[bot]
  categories:
  - title: Breaking Changes 🛠
    labels:
    - breaking-change
  - title: Exciting New Features 🎉
    labels:
    - enhancement
  - title: Documentation Updates 📚
    labels:
    - documentation
  - title: Other Changes
    labels:
    - "*"
