apiVersion: console.mia-platform.eu/v1
itemFamily: services
type: service
syncable: true
mappings:
  identifier: |-
    {{ printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum }}
  metadata:
    title: "{{ printf \"%s\" .service.name }}"
    owner: |-
      {{ $info := (get "info" .project (object)) -}}
      {{- $teamContact := (get "teamContact" $info nil) -}}
      {{- if $teamContact -}}
        {{- $owner := object -}}
        {{- $owner = set "type" "email" $owner -}}
        {{- $owner = set "ref" (get "teamContact" $info "") $owner -}}
        {{- $owner | toJSON -}}
      {{- end }}
  spec:
    projectUniqueId: "{{ .project._id }}"
    projectId: "{{ get \"projectId\" .project \"\" | quote }}"
    tenantId: "{{ .project.tenantId }}"
    revisionName: "{{ .revision.name }}"
    configuration: "{{ .service | toJSON }}"
  extra:
    - apiVersion: mia-platform.eu/v1
      itemFamily: relationships
      deletePolicy: "cascade"
      identifier: |-
        {{ $src := printf "urn:mia-platform-catalog:console.mia-platform.eu:v1:Service:%s" (printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum) -}}
        {{- $type := "urn:mia-platform-catalog:mia-platform.eu:v1:RelationshipType:part-of.mia-platform.eu" -}}
        {{- $tgt := printf "urn:mia-platform-catalog:console.mia-platform.eu:v1:Project:%s" .project._id -}}
        {{- printf "%s-%s-%s" $src $type $tgt | sha256sum }}
      sourceRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1:Service:{{ printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum }}
      targetRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1:Project:{{ .project._id }}
      typeRef: "urn:mia-platform-catalog:mia-platform.eu:v1:RelationshipType:part-of.mia-platform.eu"
    - apiVersion: mia-platform.eu/v1
      itemFamily: relationships
      deletePolicy: "cascade"
      identifier: |-
        {{ $src := printf "urn:mia-platform-catalog:console.mia-platform.eu:v1:Service:%s" (printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum) -}}
        {{- $type := "urn:mia-platform-catalog:mia-platform.eu:v1:RelationshipType:part-of.mia-platform.eu" -}}
        {{- $tgt := printf "urn:mia-platform-catalog:console.mia-platform.eu:v1:Revision:%s" (printf "%s-%s" .project._id .revision.name | sha256sum) -}}
        {{- printf "%s-%s-%s" $src $type $tgt | sha256sum }}
      sourceRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1:Service:{{ printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum }}
      targetRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1:Revision:{{ printf "%s-%s" .project._id .revision.name | sha256sum }}
      typeRef: "urn:mia-platform-catalog:mia-platform.eu:v1:RelationshipType:part-of.mia-platform.eu"
    - apiVersion: mia-platform.eu/v1
      itemFamily: relationships
      deletePolicy: "none"
      identifier: |-
        {{ $src := printf "urn:mia-platform-catalog:console.mia-platform.eu:v1:Service:%s" (printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum) -}}
        {{- $type := "urn:mia-platform-catalog:mia-platform.eu:v1:RelationshipType:dependency.mia-platform.eu" -}}
        {{- $tgt := printf "urn:mia-platform-catalog:nexus.mia-platform.eu:v1:DockerImage:%s" (printf "%s" .service.dockerImage | sha256sum) -}}
        {{- printf "%s-%s-%s" $src $type $tgt | sha256sum }}
      sourceRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1:Service:{{ printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum }}
      targetRef: |-
        urn:mia-platform-catalog:nexus.mia-platform.eu:v1:DockerImage:{{ printf "%s" .service.dockerImage | sha256sum }}
      typeRef: "urn:mia-platform-catalog:mia-platform.eu:v1:RelationshipType:dependency.mia-platform.eu"
