apiVersion: console.mia-platform.eu/v1alpha1
itemFamily: services
type: service
syncable: true
mappings:
  identifier: |-
    {{ printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum }}
  metadata:
    title: "{{ printf \"%s\" .service.name }}"
  spec:
    projectUniqueId: "{{ .project._id }}"
    projectId: "{{ get \"projectId\" .project \"\" | quote }}"
    tenantId: "{{ .project.tenantId }}"
    revisionName: "{{ .revision.name }}"
    configuration: "{{ .service | toJSON }}"
  extra:
    - apiVersion: mia-platform.eu/v1alpha1
      itemFamily: relationships
      deletePolicy: "cascade"
      identifier: |-
        {{ printf "relationship-%s-%s-belonging" (printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum) .project._id | sha256sum }}
      sourceRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1alpha1:Service:null:{{ printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum }}
      targetRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1alpha1:Project:null:{{ .project._id }}
      typeRef: "urn:mia-platform-catalog:mia-platform.eu:v1alpha1:RelationshipType:null:belonging.mia-platform.eu"
    - apiVersion: mia-platform.eu/v1alpha1
      itemFamily: relationships
      deletePolicy: "cascade"
      identifier: |-
        {{ printf "relationship-%s-%s-belonging" (printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum) (printf "%s-%s" .project._id .revision.name | sha256sum) | sha256sum }}
      sourceRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1alpha1:Service:null:{{ printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum }}
      targetRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1alpha1:Revision:null:{{ printf "%s-%s" .project._id .revision.name | sha256sum }}
      typeRef: "urn:mia-platform-catalog:mia-platform.eu:v1alpha1:RelationshipType:null:belonging.mia-platform.eu"
    - apiVersion: mia-platform.eu/v1alpha1
      itemFamily: relationships
      deletePolicy: "cascade"
      createIf: |-
        {{ $info := (get "info" .project (object)) -}}
        {{- $teamContact := (get "teamContact" $info nil) -}}
        {{- if $teamContact -}}
          true
        {{- else -}}
          false
        {{- end }}
      identifier: |-
        {{ $info := (get "info" .project (object)) -}}
        {{- $teamContact := (get "teamContact" $info "") -}}
        {{- printf "relationship-%s-%s-ownership" $teamContact (printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum) | sha256sum}}
      sourceRef: |-
        {{ $info := (get "info" .project (object)) -}}
        {{- $teamContact := (get "teamContact" $info "") -}}
        urn:mia-platform-catalog:iam.mia-platform.eu:v1alpha1:User:null:{{ $teamContact | sha256sum }}
      targetRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1alpha1:Service:null:{{ printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum }}
      typeRef: "urn:mia-platform-catalog:mia-platform.eu:v1alpha1:RelationshipType:null:ownership.mia-platform.eu"
    - apiVersion: mia-platform.eu/v1alpha1
      itemFamily: relationships
      deletePolicy: "none"
      identifier: |-
        {{ printf "relationship-%s-%s-dependency" (printf "%s" .service.dockerImage | sha256sum) (printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum) | sha256sum }}
      sourceRef: |-
        urn:mia-platform-catalog:nexus.mia-platform.eu:v1alpha1:DockerImage:null:{{ printf "%s" .service.dockerImage | sha256sum }}
      targetRef: |-
        urn:mia-platform-catalog:console.mia-platform.eu:v1alpha1:Service:null:{{ printf "%s-%s-%s" .project._id .revision.name .service.name | sha256sum }}
      typeRef: "urn:mia-platform-catalog:mia-platform.eu:v1alpha1:RelationshipType:null:dependency.mia-platform.eu"
