# yaml-language-server: $schema=https://cdn.mia-platform.eu/catalog/v1alpha1/mia-platform.eu.v1alpha1.ItemTypeDefinition.json
---
apiVersion: mia-platform.eu/v1alpha1
kind: ItemTypeDefinition
metadata:
  name: repositories.nexus.mia-platform.eu
spec:
  group: nexus.mia-platform.eu
  names:
    kind: Repository
    plural: repositories
    displayPlural: Repositories
  scope: Organization
  versions:
  - deprecated: false
    name: v1alpha1
    schema:
      openAPIV31Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                description: The unique name of the Nexus repository.
                type: string
                title: Name
              format:
                description: The repository format (e.g. maven2, docker, npm, raw, nuget).
                type: string
                title: Format
              repositoryType:
                description: The repository type (hosted, proxy, or group).
                type: string
                title: Repository Type
              url:
                description: The URL to access the repository.
                type: string
                title: URL
    served: true
    storage: true
