# yaml-language-server: $schema=https://cdn.mia-platform.eu/catalog/v1alpha1/mia-platform.eu.v1alpha1.CustomResourceDefinition.json
---
apiVersion: mia-platform.eu/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: computeinstances.gcp.mia-platform.eu
spec:
  group: gcp.mia-platform.eu
  names:
    kind: ComputeInstance
    plural: computeinstances
    singular: computeinstance
  scope: Organization
  versions:
  - deprecated: false
    name: v1alpha1
    schema:
      openAPIV31Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                description: The GCP compute instance name
                type: string
              description:
                description: Human-readable description
                type: string
              cpuPlatform:
                description: The CPU platform string
                type: string
              location:
                description: The region zone where the instance is deployed
                type: string
              status:
                description: Current status of the instance, possible values are 'provisioning', 'staging', 'running', 'stopping', 'suspending', 'suspended', or 'terminated'
                type: string
              deletionProtection:
                description: Whether the instance deletion protection is enabled
                type: boolean
              integrityMonitoringEnabled:
                description: Whether integrity monitoring is enabled
                type: boolean
              secureBootEnabled:
                description: Whether secure boot is enabled
                type: boolean
              vtpmEnabled:
                description: Whether vTPM is enabled
                type: boolean
              confidentialInstanceConfigEnabled:
                description: Whether confidential instance config is enabled
                type: boolean
              lastStart:
                description: RFC 3339 timestamp for the last start time
                type: string
                format: date-time
              machineType:
                description: The machine type of the instance
                type: string
              instancesIPs:
                description: List of the instance IPs. One or more IPs can be attached to the instance
                type: array
                items:
                  type: string
              disks:
                description: Instance disks details
                type: array
                items:
                  type: object
                  properties:
                    architecture:
                      type: string
                    autoDelete:
                      type: boolean
                    boot:
                      type: boolean
                    deviceName:
                      type: string
                    diskSizeGb:
                      type: string
                    mode:
                      type: string
                    type:
                      type: string
              network:
                description: Instance network details
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    network:
                      type: string
                    networkIP:
                      type: string
                    subnetwork:
                      type: string
              labels:
                description: User-provided labels in key-value pairs.
                type: object
                additionalProperties:
                  type: string
              tags:
                description: Network tags attached to the instance
                type: array
                items:
                  type: string
    served: true
    storage: true
