# yaml-language-server: $schema=https://cdn.mia-platform.eu/catalog/v1alpha1/miaplatform.eu.v1alpha1.CustomResourceDefinition.json
---
apiVersion: mia-platform.eu/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: sqlinstances.gcp.mia-platform.eu
spec:
  group: gcp.mia-platform.eu
  names:
    kind: SQLInstance
    plural: sqlinstances
    singular: sqlinstance
  scope: Organization
  versions:
  - deprecated: false
    name: v1alpha1
    schema:
      openAPIV31Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                description: The name of the Cloud SQL instance
                type: string
              region:
                description: Region where the instance is located
                type: string
              location:
                description: The GCP zone of the region where the primary instance is located
                type: string
              dataDiskSizeGb:
                description: Instance data disk size in GB
                type: string
              dataDiskType:
                description: The type of data disk, possible values are 'ssd', or 'hdd'.
                type: string
              storageAutoResize:
                description: Whether storage auto resize is enabled
                type: boolean
              storageAutoResizeLimit:
                description: The maximum size to which storage capacity can be automatically increased. The default value is 0, which specifies that there is no limit.
                type: integer
              installedVersion:
                description: The installed database patch/version
                type: string
              availabilityType:
                description: The availability type of the instance, possible values are 'zonal' and 'regional'.
                type: string
              serviceAccount:
                description: The service account email address assigned to the instance
                type: string
              deletionProtectionEnabled:
                description: Whether the deletion protection is enabled
                type: boolean
              state:
                description: Instance current state
                type: string
              connection:
                description: Connection settings for the instance
                type: object
                properties:
                  requireSSL:
                    type: boolean
                  sslMode:
                    type: string
                  serverCAMode:
                    type: string
                  serverCertificateRotationMode:
                    type: string
                  ipv4Enabled:
                    type: boolean
                  authorizedNetworks:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                  dns:
                    type: string
                  dnsNames:
                    type: array
                    items:
                      type: object
                      properties:
                        connectionType:
                          type: string
                        dnsScope:
                          type: string
                        name:
                          type: string
                  ipAddresses:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        ipAddress:
                          type: string
              labels:
                description: User labels assigned to the instance
                type: object
                additionalProperties:
                  type: string
    served: true
    storage: true
