// Code generated by "stringer -type=DataOperation -trimprefix Data"; DO NOT EDIT.

package source

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataOperationUpsert-0]
	_ = x[DataOperationDelete-1]
}

const _DataOperation_name = "OperationUpsertOperationDelete"

var _DataOperation_index = [...]uint8{0, 15, 30}

func (i DataOperation) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DataOperation_index)-1 {
		return "DataOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataOperation_name[_DataOperation_index[idx]:_DataOperation_index[idx+1]]
}
