apiVersion: k8s.mia-platform-experimental.eu/v1
itemFamily: pods
type: pod
syncable: true
mappings:
  identifier: |-
    {{ printf "k8s-%s-pod-%s-%s" (replace "https://" "" .apiServer) .namespace .name | sha256sum }}
  metadata:
    title: "{{ .name | toJSON }}"
  spec:
    name: "{{ .name | toJSON }}"
    namespace: "{{ .namespace | toJSON }}"
    labels: "{{ .labels | toJSON }}"
    annotations: "{{ .annotations | toJSON }}"
    creationTimestamp: "{{ .creationTimestamp | toJSON }}"
    owner: "{{ .owner | toJSON }}"
    nodeName: "{{ .nodeName | toJSON }}"
    phase: "{{ .phase | toJSON }}"
    podIP: "{{ .podIP | toJSON }}"
    startTime: "{{ .startTime | toJSON }}"
    reason: "{{ .reason | toJSON }}"
    containers: "{{ .containers | toJSON }}"
    serviceAccountName: "{{ .serviceAccountName | toJSON }}"
    hostNetwork: "{{ .hostNetwork | toJSON }}"
    hostPID: "{{ .hostPID | toJSON }}"
    hostIPC: "{{ .hostIPC | toJSON }}"
    nodeSelector: "{{ .nodeSelector | toJSON }}"
    tolerations: "{{ .tolerations | toJSON }}"
    securityContext: "{{ .securityContext | toJSON }}"
    imagePullSecrets: "{{ .imagePullSecrets | toJSON }}"
    volumes: "{{ .volumes | toJSON }}"
  extra:
    - apiVersion: mia-platform.eu/v1
      itemFamily: relationships
      deletePolicy: "cascade"
      identifier: |-
        {{ $src := printf "urn:mia-platform-catalog:k8s.mia-platform-experimental.eu:v1:Pod:%s" (printf "k8s-%s-pod-%s-%s" (replace "https://" "" .apiServer) .namespace .name | sha256sum) -}}
        {{- $type := "urn:mia-platform-catalog:mia-platform.eu:v1:RelationshipType:part-of.mia-platform.eu" -}}
        {{- $tgt := printf "urn:mia-platform-catalog:k8s.mia-platform-experimental.eu:v1:Namespace:%s" (printf "%s-%s" (replace "https://" "" .apiServer) .namespace | sha256sum) -}}
        {{- printf "%s-%s-%s" $src $type $tgt | sha256sum }}
      sourceRef: |-
        urn:mia-platform-catalog:k8s.mia-platform-experimental.eu:v1:Pod:{{ printf "k8s-%s-pod-%s-%s" (replace "https://" "" .apiServer) .namespace .name | sha256sum }}
      targetRef: |-
        urn:mia-platform-catalog:k8s.mia-platform-experimental.eu:v1:Namespace:{{ printf "%s-%s" (replace "https://" "" .apiServer) .namespace | sha256sum }}
      typeRef: "urn:mia-platform-catalog:mia-platform.eu:v1:RelationshipType:part-of.mia-platform.eu"
