---
# yaml-language-server: $schema=https://cdn.mia-platform.eu/catalog/v1alpha1/mia-platform.eu.v1alpha1.CustomResourceDefinition.json
apiVersion: mia-platform.eu/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: clusters.gcp.mia-platform.eu
spec:
  group: gcp.mia-platform.eu
  names:
    kind: Cluster
    plural: clusters
    singular: cluster
  scope: Organization
  versions:
    - deprecated: false
      name: v1alpha1
      schema:
        openAPIV31Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  description: Unique cluster identifier
                  type: string
                name:
                  description: Cluster name
                  type: string
                description:
                  description: Human-readable description of the cluster
                  type: string
                loggingService:
                  description: Configured logging service for the cluster
                  type: string
                monitoringService:
                  description: Configured monitoring service for the cluster
                  type: string
                network:
                  description: Network resource the cluster uses
                  type: string
                subnetwork:
                  description: Subnetwork resource the cluster uses
                  type: string
                addonsConfig:
                  description: Configuration for cluster add-ons
                  type: object
                  additionalProperties: true
                nodePools:
                  description: List of node pools
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      locations:
                        type: array
                        items:
                          type: string
                      version:
                        type: string
                    additionalProperties: true
                locations:
                  description: List of cluster locations or zones
                  type: array
                  items:
                    type: string
                resourceLabels:
                  description: Resource labels for the cluster
                  type: object
                  additionalProperties:
                    type: string
                networkPolicy:
                  description: Whether network policy is enabled and provider
                  type: object
                  properties:
                    provider:
                      type: string
                    enabled:
                      type: boolean
                  additionalProperties: true
                maintenancePolicy:
                  description: Maintenance windows configuration
                  type: object
                  additionalProperties: true
                autoscaling:
                  description: Autoprovisioning and autoscaling settings
                  type: object
                  properties:
                    enableNodeAutoprovisioning:
                      type: boolean
                    autoscalingProfile:
                      type: string
                    autoprovisioningLocations:
                      type: array
                      items:
                        type: string
                  additionalProperties: true
                networkConfig:
                  description: Network/subnetwork selection
                  type: object
                  properties:
                    network:
                      type: string
                    subnetwork:
                      type: string
                  additionalProperties: true
                defaultMaxPodsConstraint:
                  description: Default max pods per node
                  type: object
                  properties:
                    maxPodsPerNode:
                      type: string
                  additionalProperties: true
                databaseEncryption:
                  description: State of cluster database encryption
                  type: object
                  properties:
                    state:
                      type: string
                  additionalProperties: true
                verticalPodAutoscaling:
                  description: Vertical Pod Autoscaling enabled flag
                  type: object
                  properties:
                    enabled:
                      type: boolean
                  additionalProperties: true
                shieldedNodes:
                  description: Shielded Nodes enabled flag
                  type: object
                  properties:
                    enabled:
                      type: boolean
                  additionalProperties: true
                currentMasterVersion:
                  description: Control plane version
                  type: string
                status:
                  description: Cluster status (possible options can be PROVISIONING, RUNNING, etc.)
                  type: string
                location:
                  description: Primary location for the cluster
                  type: string
                autopilot:
                  description: Autopilot mode settings
                  type: object
                  properties:
                    enabled:
                      type: boolean
                  additionalProperties: true
                podAutoscaling:
                  description: HPA profile settings
                  type: object
                  properties:
                    hpaProfile:
                      type: string
                  additionalProperties: true
              additionalProperties: true
      served: true
      storage: true
