---
# yaml-language-server: $schema=https://cdn.mia-platform.eu/catalog/v1alpha1/mia-platform.eu.v1alpha1.CustomResourceDefinition.json
apiVersion: mia-platform.eu/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: firewalls.gcp.mia-platform.eu
spec:
  group: gcp.mia-platform.eu
  names:
    kind: Firewall
    plural: firewalls
    singular: firewall
  scope: Organization
  versions:
    - deprecated: false
      name: v1alpha1
      schema:
        openAPIV31Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  description: The user-assigned name of the firewall
                  type: string
                description:
                  description: Human-readable description of the firewall
                  type: string
                direction:
                  description: Direction of traffic this firewall applies to (possible options can be INGRESS or EGRESS)
                  type: string
                disabled:
                  description: Whether the firewall is disabled
                  type: boolean
                network:
                  description: The network this firewall applies to
                  type: string
                allowed:
                  description: Protocol and ports that are allowed by this firewall
                  type: array
                  items:
                    type: object
                    properties:
                      IPProtocol:
                        type: string
                      ports:
                        type: array
                        items:
                          type: string
                    additionalProperties: true
                targetTags:
                  description: List of instance tags the firewall rules applies to
                  type: array
                  items:
                    type: string
                updateTime:
                  description: RFC 3339 timestamp for the last update to the firewall
                  type: string
                  format: date-time
                location:
                  description: Location context when applicable
                  type: string
              additionalProperties: true
      served: true
      storage: true
