---
# yaml-language-server: $schema=https://cdn.mia-platform.eu/catalog/v1alpha1/mia-platform.eu.v1alpha1.CustomResourceDefinition.json
apiVersion: mia-platform.eu/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: revisions.run.gcp.mia-platform.eu
spec:
  group: run.gcp.mia-platform.eu
  names:
    kind: Revision
    plural: revisions
    singular: revision
  scope: Organization
  versions:
    - deprecated: false
      name: v1alpha1
      schema:
        openAPIV31Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                apiVersion:
                  description: API version of the revision resource
                  type: string
                kind:
                  description: The resource kind
                  type: string
                name:
                  description: The name of the revision
                  type: string
                uid:
                  description: Unique identifier for the revision
                  type: string
                labels:
                  description: Labels attached to the revision
                  type: object
                  additionalProperties:
                    type: string
                containers:
                  description: Containers referenced by the revision
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      resources:
                        type: object
                        properties:
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                            additionalProperties: true
                        additionalProperties: true
                    additionalProperties: true
                updateTime:
                  description: RFC 3339 timestamp for the last update to the revision
                  type: string
                  format: date-time
                location:
                  description: Region where the revision is deployed
                  type: string
                version:
                  description: Version field present in some GCP messages
                  type: string
              additionalProperties: true
      served: true
      storage: true
