---
# yaml-language-server: $schema=https://cdn.mia-platform.eu/catalog/v1alpha1/mia-platform.eu.v1alpha1.CustomResourceDefinition.json
apiVersion: mia-platform.eu/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: sqlinstances.sql.gcp.mia-platform.eu
spec:
  group: sql.gcp.mia-platform.eu
  names:
    kind: SQLInstance
    plural: sqlinstances
    singular: sql
  scope: Organization
  versions:
    - deprecated: false
      name: v1alpha1
      schema:
        openAPIV31Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                backendType:
                  description: The backend generation
                  type: string
                databaseInstalledVersion:
                  description: The installed database patch/version
                  type: string
                databaseVersion:
                  description: The major database version
                  type: string
                gceZone:
                  description: Zone where primary is located
                  type: string
                ipAddresses:
                  description: List of IP addresses associated with the instance
                  type: array
                  items:
                    type: object
                    properties:
                      ipAddress:
                        type: string
                      type:
                        type: string
                    additionalProperties: true
                kind:
                  description: Resource kind (for example, sql#instance)
                  type: string
                name:
                  description: Instance name
                  type: string
                region:
                  description: Region where the instance runs
                  type: string
                backupConfiguration:
                  type: object
                  properties:
                    backupRetentionSettings:
                      type: object
                      properties:
                        retainedBackups:
                          type: integer
                        retentionUnit:
                          type: string
                      additionalProperties: true
                    backupTier:
                      type: string
                    enabled:
                      type: boolean
                    startTime:
                      type: string
                    transactionLogRetentionDays:
                      type: integer
                  additionalProperties: true
                dataDiskSizeGb:
                  type: string
                dataDiskType:
                  type: string
                deletionProtectionEnabled:
                  type: boolean
                edition:
                  type: string
                enableGoogleMlIntegration:
                  type: boolean
                finalBackupConfig:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                  additionalProperties: true
                locationPreference:
                  type: object
                  properties:
                    zone:
                      type: string
                  additionalProperties: true
                storageAutoResize:
                  type: boolean
                storageAutoResizeLimit:
                  type: string
                userLabels:
                  type: object
                  additionalProperties:
                    type: string
                state:
                  description: Instance state (for example RUNNABLE)
                  type: string
                updateTime:
                  description: RFC 3339 timestamp for last update
                  type: string
                  format: date-time
                location:
                  description: The region where the instance is deployed
                  type: string
              additionalProperties: true
      served: true
      storage: true
