---
# yaml-language-server: $schema=https://cdn.mia-platform.eu/catalog/v1alpha1/mia-platform.eu.v1alpha1.CustomResourceDefinition.json
apiVersion: mia-platform.eu/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: services.run.gcp.mia-platform.eu
spec:
  group: run.gcp.mia-platform.eu
  names:
    kind: Service
    plural: services
    singular: service
  scope: Organization
  versions:
    - deprecated: false
      name: v1alpha1
      schema:
        openAPIV31Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                apiVersion:
                  description: API version of the resource
                  type: string
                kind:
                  description: The resource kind
                  type: string
                name:
                  description: The name of the Service
                  type: string
                uid:
                  description: Unique identifier for the Service
                  type: string
                labels:
                  description: Labels attached to the Service
                  type: object
                  additionalProperties:
                    type: string
                containerConcurrency:
                  description: Maximum number of requests a single container instance can receive concurrently
                  type: integer
                containers:
                  description: Containers defined in the service template
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      image:
                        type: string
                      ports:
                        type: array
                        items:
                          type: object
                          properties:
                            containerPort:
                              type: integer
                            name:
                              type: string
                          additionalProperties: true
                      resources:
                        type: object
                        properties:
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                            additionalProperties: true
                        additionalProperties: true
                    additionalProperties: true
                traffic:
                  description: Traffic routing configuration for the Service
                  type: array
                  items:
                    type: object
                    properties:
                      latestRevision:
                        type: boolean
                      percent:
                        type: integer
                    additionalProperties: true
                updateTime:
                  description: RFC 3339 timestamp for the last update to the service
                  type: string
                  format: date-time
                location:
                  description: Region where the service is deployed
                  type: string
              additionalProperties: true
      served: true
      storage: true
