# yaml-language-server: $schema=https://cdn.mia-platform.eu/catalog/v1alpha1/mia-platform.eu.v1alpha1.ItemTypeDefinition.json
---
apiVersion: mia-platform.eu/v1alpha1
kind: ItemTypeDefinition
metadata:
  name: folders.gcp.mia-platform.eu
spec:
  group: gcp.mia-platform.eu
  names:
    kind: Folder
    plural: folders
    displayPlural: Folders
  scope: Organization
  versions:
  - deprecated: false
    name: v1alpha1
    schema:
      openAPIV31Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                description: The folder id used to identify the folder in GCP
                type: string
                title: ID
              displayName:
                description: The user visible name for the project.
                type: string
                title: Name
              parent:
                description: The parent resource identifier (for example, 'folders/{folder_id}' or 'organizations/{org_id}')
                type: string
                title: Parent Resource
              state:
                description: Current lifecycle state of the folder. Possible values are 'state_unspecified', 'active', or 'delete_requested'.
                type: string
                title: Folder State
              createTime:
                description: RFC 3339 timestamp for when the folder was created
                type: string
                format: date-time
                title: Creation Time
              labels:
                description: User-provided labels in key-value pairs.
                type: object
                title: Labels
                additionalProperties:
                  type: string
    served: true
    storage: true
