# yaml-language-server: $schema=https://cdn.mia-platform.eu/catalog/v1alpha1/mia-platform.eu.v1alpha1.ItemTypeDefinition.json
---
apiVersion: mia-platform.eu/v1alpha1
kind: ItemTypeDefinition
metadata:
  name: firewallrules.gcp.mia-platform.eu
spec:
  group: gcp.mia-platform.eu
  names:
    kind: FirewallRule
    plural: firewallrules
    displayPlural: FirewallRules
  scope: Organization
  versions:
  - deprecated: false
    name: v1alpha1
    schema:
      openAPIV31Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                description: The user-assigned name for the firewall rule
                type: string
                title: Name
              description:
                description: Human-readable description of the firewall rule
                type: string
                title: Description
              disabled:
                description: Whether the firewall rule is disabled
                type: boolean
                title: Rule Disabled
              network:
                description: The network self link this firewall rule applies to
                type: string
                title: GCP Network URL
              priority:
                description: Priority of the firewall rule
                type: integer
                title: Rule Priority
              logEnabled:
                description: Whether logging is enabled for this firewall rule
                type: boolean
                title: Logging Enabled
              ingress:
                description: If the rule is an ingress, this property will contains the firewall rule ingress configuration
                type: object
                title: Ingress Configuration
                properties:
                  allowed:
                    description: List of allowed protocols and ports
                    type: array
                    title: Allowed Rule
                    items:
                      type: object
                      properties:
                        IPProtocol:
                          description: The IP protocol of this allowed rule
                          type: string
                          title: IP Protocol
                        ports:
                          description: List of ports or port ranges
                          type: array
                          title: Ports
                          items:
                            type: string
                  denied:
                    description: List of denied protocols and ports
                    type: array
                    title: Denied Rule
                    items:
                      type: object
                      properties:
                        IPProtocol:
                          description: The IP protocol of this denied rule
                          type: string
                          title: IP Protocol
                        ports:
                          description: List of ports or port ranges
                          type: array
                          title: Ports
                          items:
                            type: string
                  sourceRanges:
                    description: List of source IP address ranges
                    type: array
                    title: Source IP Ranges
                    items:
                      type: string
                  sourceTags:
                    description: List of source tags
                    type: array
                    title: Source Tags
                    items:
                      type: string
                  sourceServiceAccounts:
                    description: List of source service accounts
                    type: array
                    title: Source Service Accounts
                    items:
                      type: string
                  targetRanges:
                    description: List of target IP address ranges
                    type: array
                    title: Target IP Ranges
                    items:
                      type: string
                  targetTags:
                    description: List of target tags
                    type: array
                    title: Target Network Tags
                    items:
                      type: string
                  targetServiceAccounts:
                    description: List of target service accounts
                    type: array
                    title: Target Service Accounts
                    items:
                      type: string
                  destinationRanges:
                    description: List of destination IP address ranges
                    type: array
                    title: Destination IP Ranges
                    items:
                      type: string
              egress:
                description: If the rule is an egress, this property will contains the firewall rule egress configuration
                type: object
                title: Egress Configuration
                properties:
                  allowed:
                    description: List of allowed protocols and ports
                    type: array
                    title: Allowed Rule
                    items:
                      type: object
                      properties:
                        IPProtocol:
                          description: The IP protocol of this allowed rule
                          type: string
                          title: IP Protocol
                        ports:
                          description: List of ports or port ranges
                          type: array
                          title: Ports
                          items:
                            type: string
                  denied:
                    description: List of denied protocols and ports
                    type: array
                    title: Denied Rule
                    items:
                      type: object
                      properties:
                        IPProtocol:
                          description: The IP protocol of this denied rule
                          type: string
                          title: IP Protocol
                        ports:
                          description: List of ports or port ranges
                          type: array
                          title: Ports
                          items:
                            type: string
                  sourceRanges:
                    description: List of source IP address ranges
                    type: array
                    title: Source IP Ranges
                    items:
                      type: string
                  sourceTags:
                    description: List of source tags
                    type: array
                    title: Source Tags
                    items:
                      type: string
                  sourceServiceAccounts:
                    description: List of source service accounts
                    type: array
                    title: Source Service Accounts
                    items:
                      type: string
                  targetRanges:
                    description: List of target IP address ranges
                    type: array
                    title: Target IP Ranges
                    items:
                      type: string
                  targetTags:
                    description: List of target tags
                    type: array
                    title: Target Network Tags
                    items:
                      type: string
                  targetServiceAccounts:
                    description: List of target service accounts
                    type: array
                    title: Target Service Accounts
                    items:
                      type: string
                  destinationRanges:
                    description: List of destination IP address ranges
                    type: array
                    title: Destination IP Ranges
                    items:
                      type: string
              location:
                description: Location of the firewall rule. It will be always 'global'
                type: string
                title: GCP Location
    served: true
    storage: true
